config/routes.rb
Rails.application.routes.draw do
  root :to => "catalog#index"
  blacklight_for :catalog
  devise_for :users

  resource :contact, :only => [:show, :create]

  get '/admin', :to => 'admin#index', :as => "admin_index"

  get '/about', :to => 'about#index', :as => "about_us"

  get '/help', :to => 'help#index', :as => "help"

  namespace :admin do
    resources :users
    resources :art_pieces
    resources :artists
    resources :buildings
    resources :collections
    resources :settings
    resources :media
    resources :series
  end
end

app/views/admin/index.html.erb
<div class="container" align="center">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-default" id="dashboard">
        <div class="panel panel-heading"> Administration Dashboard </div>
        <div class="panel panel-body">
          <p><%= link_to "Update User Status", admin_users_path %></p>
          <p><%= link_to "Art Piece Information", admin_art_pieces_path %></p>
          <p><%= link_to "Artist Information", admin_artists_path %></p>
          <p><%= link_to "Building Information", admin_buildings_path %></p>
          <p><%= link_to "Collection Information", admin_collections_path %></p>
          <p><%= link_to "Series Information", admin_series_index_path %></p>
          <p><%= link_to "Medium Information", admin_media_path %></p>
          <p><%= link_to "Settings", admin_settings_path %></p>
          <p><%= link_to "Export Art Piece Info To CSV", admin_art_pieces_path(format: "csv") %></p>
        </div>
      </div>
    </div>
  </div>
</div>