config/routes.rb
Rails.application.routes.draw do
  root :to => "catalog#index"
  blacklight_for :catalog
  devise_for :users

  resource :contact, :only => [:show, :create]

  get '/admin', :to => 'admin#index', :as => "admin_index"

  get '/about', :to => 'about#index', :as => "about_us"

  get '/help', :to => 'help#index', :as => "help"

  namespace :admin do
    resources :users
    resources :art_pieces
    resources :artists
    resources :buildings
    resources :collections
    resources :settings
    resources :media
    resources :series
  end
end

app/models/art_piece.rb
class ArtPiece < ActiveRecord::Base
  include SunspotModel
  include MakeSearchable

  validates :title, :presence => true 


  #Art Piece Building associations
  has_one :building, :through => :art_piece_building
  has_one :art_piece_building

  #Art Piece Artists associations
  has_many :artists, :through => :art_piece_artists
  has_many :art_piece_artists

  #Art Piece Collections associations
  has_many :collections, :through => :art_piece_collections
  has_many :art_piece_collections

  #Art Piece Photo associations
  has_many :art_piece_photos

  #Medium association
  has_many :media, :through => :art_piece_media
  has_many :art_piece_media

  # Series
  has_many :series, :through => :art_piece_series
  has_many :art_piece_series

  #Delegations
  delegate :name, :coords, :description, :lat, :long, :to => :building, :prefix => true, :allow_nil => true
  delegate :collection_url, :to => :collections, :prefix => true, :allow_nil => true
  delegate :location, :position_num, :floor, :to => :art_piece_building, :prefix => true, :allow_nil => true


  accepts_nested_attributes_for :art_piece_photos, :art_piece_building, :allow_destroy => true

  class << self
    def to_csv
      ArtPieceCSVGenerator.new(self).run
    end
  end

  def status
    status = []
    status << I18n.t('art_piece.faculty_string') if by_faculty?
    status << I18n.t('art_piece.student_string') if by_student?
    status
  end

  def display_status
    display = ""
    display = I18n.t('art_piece.on_display_string') if displayed?
    display = I18n.t('art_piece.not_on_display_string') if !displayed?
    display
  end

  def coords
    return nil if lat.blank? || long.blank?
    [title, lat, long].join("-|-")
  end

  def collection_urls
    collections.map(&:collection_url)
  end
  
  private

  def by_faculty?
    artists.find{|x| x.faculty?}.present?
  end

  def by_student?
    artists.find{|x| x.student?}.present?
  end

end

app/models/art_pieces.rb
class ArtPieces < ActiveRecord::Base

  validates :title, :presence => true 
end

app/controllers/admin/art_pieces_controller.rb
class Admin::ArtPiecesController < AdminController
  respond_to :html, :json
  before_filter :find_art_piece, :only => [:edit, :update, :destroy]
  
  def index
    @art_pieces = PaginatingDecorator.new(ArtPiece.order(:title => :asc).includes(:art_piece_photos).page(params[:page]))
    @art = ArtPiece.all
    respond_to do |format|
      format.html
      format.json
      format.csv { send_data @art.to_csv }
    end
  end

  def edit
  end

  def update
    @art_piece.update_attributes(art_piece_params)
    respond_with @art_piece, :location => admin_art_pieces_path
  end

  def destroy
    if @art_piece.destroy
      flash[:success] = "Sucessfully deleted."
    else 
      flash[:error] = "Error in deleting art piece."
    end
    respond_with [:admin, @art_piece]
  end

  def new
    @art_piece = ArtPiece.new
    @art_piece.art_piece_photos.build
    @art_piece.build_art_piece_building
  end

  def create
    @art_piece = ArtPiece.new(art_piece_params)
    flash[:success] = "Successfully created art piece!" if @art_piece.save
    respond_with @art_piece, :location => admin_art_pieces_path
  end

  private

  def find_art_piece
    @art_piece = ArtPiece.includes(:art_piece_photos).find(params[:id])
  end

  def art_piece_params
    params.require(:art_piece).permit(:title, :global_photo_credit, :creation_date, :size, :legal_info, :private, :contact_info, :description, :artist_comments, :displayed, :number, :lat, :long, :building, art_piece_photo_ids:[], art_piece_photos_attributes: [:photo, :photo_credit, :id, :_destroy], art_piece_building_attributes: [:building_id, :location, :art_piece_id, :position_num, :id], artist_ids: [], collection_ids:[], series_ids:[], medium_ids:[])
  end
end

app/views/admin/art_pieces/_art_piece_form.html.erb
<%= simple_form_for([:admin, @art_piece], :html => {:class => 'form-horizontal'}) do |f| %>
    <%= f.input :title %>
    <%= f.input :creation_date %>
    <%= f.input :size %>
    <%= f.input :legal_info %>
    <%= f.input :private %>
    <%= f.input :contact_info %>
    <%= f.input :description %>
    <%= f.input :artist_comments %>
    <%= f.input :displayed %>
    <%= f.input :number %>
    <%= f.input :lat %>
    <%= f.input :long %>
    <%= f.association :media, :label_method => :medium %>
    <%= f.association :artists %>
    <%= f.association :collections %>
    <%= f.association :series %>
    <%= f.fields_for :art_piece_building do |builder| %>
      <%= builder.input :building_id, :collection => Building.all, :label => "Building" %>
      <%= builder.input :location, :label => "Location" %>
      <%= builder.input :position_num, :label => "Position Number" %>
      <%= builder.input :art_piece_id, :as => :hidden %>
    <% end %>
    <%= f.input :global_photo_credit %>
    <%= f.simple_fields_for :art_piece_photos do |builder| %>
      <%= render :partial => "photo_form", :locals => {f: builder} %>
    <% end %>
    <%= link_to_add_fields "Add Another Photo", f, :art_piece_photos %>
    <%= f.button :submit %>
<% end %>

app/views/admin/art_pieces/_index_art_pieces.html.erb
<% @art_pieces.each do |art| %>
  <div class="panel <%= art.panel_class %>" id="piece-<%= art.id %>">
    <div class="panel panel-heading">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= art.id %>">
        <%= art.title %>
        <%= link_to "Edit", edit_admin_art_piece_path(art), :class => "pull-right", :style => "padding-left: 10px;" %>
        <%= link_to "Delete", admin_art_piece_path(art), :class => "pull-right", :method => :delete, :data => {:confirm => "Are you sure?"} %>
      </a>
    </div>
    <div class="panel-collapse collapse" id="collapse-<%= art.id %>">
      <div class="panel panel-body">
        <p>Artists: <%= art.artists.map(&:name).join(", ") %></p>
        <p>Artist Comments: <%= art.artist_comments %></p>
        <p>Description: <%= art.description %></p>
        <p>Medium: <%= art.media.map(&:medium).join(', ') %> </p>
        <p>Created On: <%= art.creation_date %></p>
        <p>Size: <%= art.size %></p>
        <p>Created On: <%= art.creation_date %></p>
        <p>Legal Info: <%= art.legal_info %></p>
        <p>Private Piece Status: <%= art.private? %></p>
        <p>Lat: <%= art.lat %></p>
        <p>Long: <%= art.long %></p>
        <% if art.private? %>
          <p>Contact Info: <%= art.contact_info %></p>
        <% end %>
        <p>On Display Status: <%= art.display_status %></p>
        <% if art.art_piece_building %>
          <p>Location Information:<br>
            <ul>
              <li>Building: <%= art.building_name %><br></li>
              <li>Location In Building: <%= art.art_piece_building.location %><br></li>
              <li>Position In Building: <%= art.art_piece_building.position_num %></li>
            </ul>
          </p>
        <% end %>
        <% if art.art_piece_photos.length > 0 %>
          <p>Photos: <% art.art_piece_photos.each do |p| %>
            <%= image_tag p.photo_url(:thumb) %>
            <%= p.photo_credit %>
          <% end %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @art_pieces, :window => 2 %>

app/views/admin/art_pieces/_photo_form.html.erb
<div id="picture">
  <div class="fields">
    <%= f.input :photo, :as => :file, :required => false unless f.object.photo_url %>
    <%= image_tag f.object.photo_url(:thumb) if f.object.photo_url %>
    <%= f.input :photo_credit %>
    <%= f.hidden_field :_destroy %>
    <%= link_to_remove_fields "remove", f %>
  </div>
</div>

app/views/admin/art_pieces/edit.html.erb
<h1> Edit </h1>
<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <%= render "art_piece_form" %>
    </div>
    <div class="col-xs-4">

    </div>
  </div>
</div>

app/views/admin/art_pieces/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1> Edit Art Piece Information </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-8">
      <div class="panel-group" id="accordion">
        <% if @art_pieces.count == 0 %>
        No Art Pieces Currently In The Database
        <% else %>
        <%= render "index_art_pieces" %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="panel panel-default">
        <div class="panel panel-heading">
          Add New
        </div>
        <div class="panel panel-body">
          <%= link_to "Add Art Piece", new_admin_art_piece_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/art_pieces/new.html.erb
<h1> New </h1>
<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <%= render "art_piece_form" %>
    </div>
    <div class="col-xs-4">

    </div>
  </div>
</div>