config/routes.rb
Rails.application.routes.draw do
  root :to => "catalog#index"
  blacklight_for :catalog
  devise_for :users

  resource :contact, :only => [:show, :create]

  get '/admin', :to => 'admin#index', :as => "admin_index"

  get '/about', :to => 'about#index', :as => "about_us"

  get '/help', :to => 'help#index', :as => "help"

  namespace :admin do
    resources :users
    resources :art_pieces
    resources :artists
    resources :buildings
    resources :collections
    resources :settings
    resources :media
    resources :series
  end
end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
#

class CatalogController < ApplicationController

  include Blacklight::Catalog
  include ArtWalk::Catalog::IndexConfiguration
  include ArtWalk::Catalog::FacetConfiguration
  include ArtWalk::Catalog::ShowConfiguration
  include ArtWalk::Catalog::MapConfiguration
  include ArtWalk::Catalog::SearchConfiguration

  rescue_from ArtWalk::Exceptions::AccessDenied, :with => :no_permissions

  before_filter :load_map_results, :only => :index

  #filter out not-diplayed art pieces
  self.solr_search_params_logic += [:exclude_not_displayed_items]
  self.solr_search_params_logic += [:require_coordinates]

  configure_blacklight do |config|
    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    config.default_solr_params = { 
      :qt => "search",
      :rows => 10
    }
    
    # If there are more than this many search results, no spelling ("did you 
    # mean") suggestion is offered.
    config.spell_max = 5
    config.add_facet_fields_to_solr_request!
  end

  def show
    super
    @map_results = [@document]
  end

  def track
    search_session['counter'] = params[:counter]
    search_session['per_page'] = params[:per_page]

    path = if params[:redirect] and (params[:redirect].starts_with?("/") or params[:redirect] =~ URI::regexp)
             params[:redirect]
           else
             { action: 'show' }
           end
    redirect_to path, :status => 303
  end

  protected

  def cleaned_params
    params_copy = params.reject { |k,v| blacklisted_search_session_params.include?(k.to_sym) or v.blank? }

    params_copy.reject { |k,v| [:action, :controller].include? k.to_sym }
  end
  helper_method :cleaned_params


  private

  def load_map_results
    @map_results = get_search_results(params.merge(:map_view => true), {:start => 0, :rows => 10000, :sort => "art_piece_building_position_num_is asc"}).first.docs unless params[:controller] == "bookmarks"
  end

  def exclude_not_displayed_items(solr_params, user_params)
    unless current_or_guest_user.admin?
      solr_params[:fq] ||= []
      solr_params[:fq] << "-displayed_bs:false"
    end
  end

  def require_coordinates(solr_params, user_params)
    return unless user_params[:map_view]
    solr_params[:fq] ||= []
    solr_params[:fq] << "coords_sms:['' TO *]"
  end

  def check_admin(document)
    unless current_or_guest_user.admin?
      raise ArtWalk::Exceptions::AccessDenied unless document['displayed_bs']
    end
  end

  def get_solr_response_for_doc_id(*args)
    solr_response, document = super
    check_admin(document)
    return [solr_response, document]
  end

  def no_permissions
    flash[:error] = I18n.t('permission_error.error_string')
    redirect_to root_path
  end

end 

app/views/catalog/_admin_show_tools.html.erb
<% if current_user && current_user.admin? %> 
  <div class="panel panel-default show-tools">
    <div class="panel-heading">
      Admin
    </div>

    <div class="panel-body">
      <ul class="nav">
          <li>
             <%= link_to "Edit This Art Piece", edit_admin_art_piece_path(@document[:id].gsub('ArtPiece ','')) %>
          </li>
          <li>
            <%= link_to "Delete This Art Piece", admin_art_piece_path(@document[:id].gsub('ArtPiece ','')), :method => :delete, :data => {:confirm => "Are you sure?"} %>
          </li>
      </ul>
    </div>
  </div>
<% end %> 

app/views/catalog/_carousel.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2 col-sm-2"></div>
    <div class="col-lg-6 col-sm-6">
      <div id="my-carousel" class="carousel slide"><!-- class of slide for animation -->
        <div class="carousel-inner">
          <% Array.wrap(document["art_piece_photos_sms"]).each_with_index do |photo, index| %>
            <div class="item <%= "active" if index == 0 %>">
              <a href="<%= photo %>" id="photo-<%= index %>" data-toggle="lightbox" data-gallery="multiimages" data-parent=".carousel-inner">
              <%= image_tag photo %>
              <div class="carousel-caption">
                <p><% if !Array.wrap(document["art_piece_photo_credit_sms"]).at(index).blank? %>
                  <%= Array.wrap(document["art_piece_photo_credit_sms"]).at(index) %>
                <% else %>
                  <%= document["global_photo_credit_ss"] %>
                <% end %></p>
              </div>
              </a>
            </div>
          <% end %>
        </div>
        <% if Array.wrap(document["art_piece_photos_sms"]).count > 1 %>
          <a class="carousel-control left" href="#my-carousel" data-slide="prev" role="button" ><span class="glyphicon glyphicon-chevron-left"></span></a>
          <a class="carousel-control right" href="#my-carousel" data-slide="next" role="button"><span class="glyphicon glyphicon-chevron-right"></span></a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/catalog/_document_maps.html.erb
<% # container for all documents in map view -%>
<div id="documents" class="map">
  <%= blacklight_map_tag('blacklight-map') {} %>
  <div id="blacklight-map-sidebar"></div>
  <%= javascript_tag "$('#blacklight-map').blacklight_leaflet_map(#{serialize_geojson});" %>
</div>

app/views/catalog/_facets.html.erb
<% # main container for facets/limits menu -%>
<% if has_facet_values?  %>
<div id="facets" class="facets sidenav">

  <div class="top-panel-heading panel-heading">
    <button type="button" class="facets-toggle theButton" data-toggle="collapse" data-target="#facet-panel-collapse">
      <span class="sr-only">Toggle facets</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

  <h4>
    <%= t('blacklight.search.facets.title') %>
  </h4>
    </div>

  <div id="facet-panel-collapse" class="collapse in panel-group">
  <%= render_facet_partials %>
</div>
</div>
<% end %>

app/views/catalog/_home_text.html.erb
<div id="welcomeSection">
  <div class="row">
    <div class="col-xs-4 col-xs-5-offset col-md-2 col-md-5-offset horizontalLine">
      <div class="largerFont" align="left">Welcome</div>
    </div>
  </div>
  <div class="row">
    <div class='col-xs-12 col-md-7 col-md-5-offset col-lg-12 noLeftPadding'>
      <%= raw Setting.Home %>
    </div>
  </div>
</div>

<% # container for all documents in map view -%>
<div id="documents" class="map">
  <%= render "map" %>
</div>

app/views/catalog/_index_maps.html.erb
<% # the way each document will be viewed in the sidebar list -%>
<li class='media'>
<div class="panel panel-<%= document[:displayed_bs] ? 'default' : 'danger' %>">
    <div class="panel-heading" id="art-piece-panel">
      <div class="panel-title">
        <h4 class='media-heading'>
          <%= link_to_map_document document, {:label => document_show_link_field(document), :counter => map_counter(document), :search_context => map_building(document)} %>
        </h4>
      </div>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-xs-3">
          <%= render_thumbnail_img document, {:class => "sidebar-thumb media-object pull-left"}, {:label => document_show_link_field(document), :counter => map_counter(document), :search_context => map_building(document)} if document[:art_piece_photos_sms] %>
        </div>
        <div class="col-xs-8">
          <% if document[:artists_sms] %>
            By <%= document[:artists_sms].join(", ") %>
            <br>
            <br>
          <% end %>
          <% if document[:number_ss].present? %>
            Plaque Number: <%= document[:number_ss] %>
            <br>
          <% end %>
          <% if document[:art_piece_building_location_ss].present? %>
            Location: <%= document[:art_piece_building_location_ss] %>
          <% end %>
        </div>
        <div class="col-xs-1"></div>
      </div>
    </div>
  </div>
</li>

app/views/catalog/_lightbox_init.html.erb
<script>
  $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
    event.preventDefault();
    $(this).ekkoLightbox();
  });
</script>

app/views/catalog/_map.html.erb
<%= blacklight_map_tag('blacklight-map') {}%>
<div id="blacklight-map-sidebar"></div>
<%= javascript_tag "window.map_data = #{serialize_geojson}" %>

app/views/catalog/_original_show_tools.html.erb
<%-
  # Compare with render_document_functions_partial helper, and
  # _document_functions partial. BL actually has two groups
  # of document-related tools. "document functions" by default
  # contains Bookmark functionality shown on both results and
  # item view. While "document tools" contains external export type
  # functions by default only on detail.

-%>
<div class="panel panel-default show-tools">
  <div class="panel-heading">
    <%= t('blacklight.tools.title') %>
  </div>

  <div class="panel-body">
  <ul class="nav">
      <li>
        <%= render_show_doc_actions @document %>
      </li>
      <% if (@document.respond_to?(:export_as_mla_citation_txt) || @document.respond_to?(:export_as_apa_citation_txt)) %>
        <li class="cite">
         <%= link_to t('blacklight.tools.cite'), citation_catalog_path(:id => @document), {:id => 'citeLink', :data => {:ajax_modal => "trigger"}} %>
        </li>
      <% end %>
      <% if @document.export_formats.keys.include?( :refworks_marc_txt ) %>
        <li class="refworks">
        <%= link_to t('blacklight.tools.refworks'), refworks_export_url(url: polymorphic_url(url_for_document(@document), format: :refworks_marc_txt, only_path: false))  %>        
        </li>
     <% end %>
     <% if @document.export_formats.keys.include?( :endnote ) %>
      <li class="endnote">
      <%= link_to t('blacklight.tools.endnote'), catalog_path(@document, :format => 'endnote') %>
      </li>
    <% end %>
    <% if @document.respond_to?( :to_email_text ) %>
      <li class="email">
      <%= link_to t('blacklight.tools.email'), email_catalog_path(:id => @document), {:id => 'emailLink', :data => {:ajax_modal => "trigger"}} %>
      </li>
    <%- end -%>
    <%- if @document.respond_to?( :to_sms_text ) -%>
      <li class="sms">
      <%= link_to t('blacklight.tools.sms'), sms_catalog_path(:id => @document), {:id => 'smsLink', :data => {:ajax_modal => "trigger"}} %>
      </li>
    <%- end -%>
    
    <% if respond_to? :librarian_view_catalog_path and @document.respond_to?(:to_marc) %>
      <li class="librarian_view">
        <%= link_to t('blacklight.tools.librarian_view'), librarian_view_catalog_path(@document), {:id => 'librarianLink', :data => {:ajax_modal => "trigger"}} %>
      </li>
    <% end %>
  </ul>
  </div>
</div>

app/views/catalog/_results_pagination.html.erb
<% if @response.total_pages > 1 %>
 <div class="row record-padding">
  <div class="col-md-9"> 
    <div class="pagination">
      <%= paginate @response, :window => 2, :theme => 'blacklight' %>
    </div>
  </div>
 </div>
<% end %>

app/views/catalog/_show_default.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="#carousel-pane" role="tab" data-toggle="tab">Carousel</a></li>
      <li><a href="#map-pane" role="tab" data-toggle="tab">Map</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="carousel-pane">
        <div class="col-xs-12" >
          <%= render :partial => "carousel", :locals => {document: document} %>
        </div>
      </div>
      <div class="tab-pane" id="map-pane">
        <div class="col-xs-6">
          <div class="map">
            <%= render "map" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%# default partial to display solr document fields in catalog show view -%>
<dl class="dl-horizontal  dl-invert">
  <% if document['artists_sms'] != nil %> 
    <% document['artists_sms'].each_with_index do |artist, i| %>
      <dt> Artist: <dd> <%= artist %> </dd> </dt>
      <% if document['artist_bio_sms'][i].present? %>
        <dt> Artist Bio: <dd> <%= document['artist_bio_sms'][i] %> </dd> </dt>
      <% end %>
    <% end %>
  <% end %>
</dl>
<dl class="dl-horizontal  dl-invert">
  <% if document['collections_sms'] != nil %> 
    <% document['collections_sms'].each_with_index do |collection, i| %>
      <% if document['collection_url_sms'][i].present? %>
        <dt> Collection: <dd> 
        <a href='<%= document["collection_url_sms"].first %>'>
          <%= document['collections_sms'][i] %>
        </a> </dd> </dt>
      <% end %>
    <% end %>
  <% end %>
</dl>
<dl class="dl-horizontal  dl-invert">
  <% document_show_fields(document).each do |solr_fname, field| -%>
    <% if should_render_show_field?(document, field) %>
	    <dt class="blacklight-<%= solr_fname.parameterize %>"><%= render_document_show_field_label document, :field => solr_fname %></dt>
	    <dd class="blacklight-<%= solr_fname.parameterize %>"><%= render_document_show_field_value document, :field => solr_fname %></dd>
    <% end -%>
  <% end -%>
</dl>

app/views/catalog/_show_tools.html.erb
<%= render 'original_show_tools' %>
<%= render 'admin_show_tools' %> 