config/routes.rb
Rails.application.routes.draw do
  root :to => "catalog#index"
  blacklight_for :catalog
  devise_for :users

  resource :contact, :only => [:show, :create]

  get '/admin', :to => 'admin#index', :as => "admin_index"

  get '/about', :to => 'about#index', :as => "about_us"

  get '/help', :to => 'help#index', :as => "help"

  namespace :admin do
    resources :users
    resources :art_pieces
    resources :artists
    resources :buildings
    resources :collections
    resources :settings
    resources :media
    resources :series
  end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :art_pieces, :through => :art_piece_collections
  has_many :art_piece_collections
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < ApplicationController
  respond_to :html, :json
  before_filter :find_collection, :only => [:edit, :update, :destroy]

  def index
    @collections = Collection.all
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)
    flash[:success] = "Successfully created collection!" if @collection.save
    respond_with @collection, :location => admin_collections_path
  end

  def edit
  end

  def update
    @collection.update_attributes(collection_params)
    respond_with @collection, :location => admin_collections_path
  end

  def destroy
    if @collection.destroy
      flash[:success] = "Sucessfully deleted."
    else 
      flash[:error] = "Error in deleting collection."
    end
    respond_with [:admin, @collection]
  end

  private

  def collection_params
    params.require(:collection).permit(:name, :collection_url)
  end

  def find_collection
    @collection = Collection.find(params[:id])
  end
end

app/views/admin/collections/_collection_form.html.erb
<%= simple_form_for([:admin, @collection], html: {class: 'form-horizontal'}) do |f| %>
    <%= f.input :name %>
    <%= f.input :collection_url %>
    <%= f.button :submit %>
<% end %>

app/views/admin/collections/_index_collections.html.erb
<% @collections.each do |collection| %>
  <div class="panel panel-default" id="collection-<%= collection.id %>">
    <div class="panel panel-heading">
      <p>Name of Collection: <%= collection.name %>
      <%= link_to "Edit", edit_admin_collection_path(collection), :class => "pull-right", :style => "padding-left: 10px;" %>
      <%= link_to "Delete", admin_collection_path(collection), :class => "pull-right", :method => :delete, :data => {:confirm => "Are you sure?"} %></p>
    </div>
    <div class='panel panel-body'>
      Collection Location: <%= collection.collection_url %> 
    </div>
  </div>
<% end %>

app/views/admin/collections/edit.html.erb
<h1> Edit </h1>
<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <%= render "collection_form" %>
    </div>
    <div class="col-xs-4">

    </div>
  </div>
</div>

app/views/admin/collections/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1> Edit Collection Information </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-8">
      <div class="panel-group" id="accordion">
        <% if @collections.count == 0 %>
        No Collections Found In Database
        <% else %>
        <%= render "index_collections" %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="panel panel-default">
        <div class="panel panel-heading">
          Add New
        </div>
        <div class="panel panel-body">
          <%= link_to "Add Collection", new_admin_collection_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/collections/new.html.erb
<h1> New </h1>
<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <%= render "collection_form" %>
    </div>
    <div class="col-xs-4">

    </div>
  </div>
</div>